import asyncio
import json
import uuid
from datetime import UTC, datetime

from redis.asyncio import Redis

USB_EVENT_STREAM = "hrip.events.usb"
NETWORK_EVENT_STREAM = "hrip.events.network"
FILE_ACCESS_STREAM = "hrip.events.file_access"
CLIPBOARD_EVENT_STREAM = "hrip.events.clipboard"
LOGIN_EVENT_STREAM = "hrip.events.login"

import os

async def test_triage_pipeline():
    redis_url = os.environ.get("REDIS_URL", "redis://localhost:6379/0")
    redis = Redis.from_url(redis_url, decode_responses=True)
    
    # 1. USB Event (Suspicious)
    usb_event = {
        "event_id": str(uuid.uuid4()),
        "username": "analyst@example.com",
        "device_name": "SanDisk Cruzer Force",
        "vid_pid": "0781:557d",
        "action": "file_copied",
        "file_size_bytes": 105000000,
        "timestamp": datetime.now(UTC).isoformat()
    }
    
    # 2. File Access Event (Suspicious)
    file_event = {
        "event_id": str(uuid.uuid4()),
        "username": "cfo@example.com",
        "file_path": "Z:/Finance/Q3_Earnings_Draft.xlsx",
        "action": "mass_download",
        "timestamp": datetime.now(UTC).isoformat()
    }
    
    # 3. Clipboard Event (Suspicious)
    clipboard_event = {
        "event_id": str(uuid.uuid4()),
        "username": "ops.manager@example.com",
        "content_type": "credential_pattern",
        "size_bytes": 1024,
        "patterns_detected": ["credit_card", "api_key"],
        "source_app": "KeePass",
        "dest_app": "chrome.exe",
        "timestamp": datetime.now(UTC).isoformat()
    }

    # 4. Login Event (Suspicious)
    login_event = {
        "event_id": str(uuid.uuid4()),
        "username": "analyst@example.com",
        "ip_address": "193.168.1.5",
        "status": "failed",
        "reason": "off_hours",
        "timestamp": datetime.now(UTC).isoformat()
    }

    events = [
        (USB_EVENT_STREAM, usb_event),
        (FILE_ACCESS_STREAM, file_event),
        (CLIPBOARD_EVENT_STREAM, clipboard_event),
        (LOGIN_EVENT_STREAM, login_event)
    ]

    print("Publishing test events to Redis Streams...")
    for stream, payload in events:
        event_id = payload.get("event_id")
        redis_payload = {
            "payload": json.dumps(payload),
            "event_id": event_id
        }
        resp = await redis.xadd(stream, redis_payload)
        print(f"Published to {stream}: {resp}")
        
    print("Done! Check the AI Review Queue in the UI to see the flags generated by Qwen.")

if __name__ == "__main__":
    asyncio.run(test_triage_pipeline())
