"""phase2_risk

Revision ID: d916336157dd
Revises: 0001_initial
Create Date: 2026-07-04 19:37:13.132005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd916336157dd'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_modules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('threat_type', sa.String(length=50), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('reading_material_url', sa.String(length=500), nullable=True),
    sa.Column('quiz_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('threat_type')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('old_score', sa.Float(), nullable=False),
    sa.Column('new_score', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('analyst_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_user_id'), 'risk_events', ['user_id'], unique=False)
    op.create_table('training_assignments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('module_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quiz_score', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['training_modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_assignments_user_id'), 'training_assignments', ['user_id'], unique=False)
    op.alter_column('alerts', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('alerts', 'message_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('alerts', 'detection_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('alerts', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.add_column('detection_features', sa.Column('feature_string', sa.Text(), nullable=True))
    op.alter_column('detection_features', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('detection_features', 'detection_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('detections', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('detections', 'message_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('inbox_events', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('message_metadata', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('message_metadata', 'message_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('outbox_events', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('risk_scores', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.alter_column('risk_scores', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    op.add_column('users', sa.Column('risk_tier', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('data_access_level', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('score_manually_set', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('score_override_by', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('score_override_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('score_override_note', sa.Text(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(as_uuid=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('users', 'score_override_note')
    op.drop_column('users', 'score_override_at')
    op.drop_column('users', 'score_override_by')
    op.drop_column('users', 'score_manually_set')
    op.drop_column('users', 'data_access_level')
    op.drop_column('users', 'risk_tier')
    op.alter_column('risk_scores', 'user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('risk_scores', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('outbox_events', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('message_metadata', 'message_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('message_metadata', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('inbox_events', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('detections', 'message_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('detections', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('detection_features', 'detection_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('detection_features', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('detection_features', 'feature_string')
    op.alter_column('alerts', 'user_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('alerts', 'detection_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('alerts', 'message_id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('alerts', 'id',
               existing_type=sa.UUID(as_uuid=False),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_training_assignments_user_id'), table_name='training_assignments')
    op.drop_table('training_assignments')
    op.drop_index(op.f('ix_risk_events_user_id'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_table('training_modules')
    # ### end Alembic commands ###
